Repository yong2gether/FE, pull requests merged in 2025-08, with the labels that each got.

#10 Feat: 회원가입 페이지, 선호 카테고리 페이지 디자인
  src/Components/PublicDropdown.jsx
  src/Components/PublicInput.jsx
  src/Data/Categories.js
  src/Pages/CategoryIndustry.jsx
  src/Pages/CategoryRegion.jsx
  src/Pages/CategoryResult.jsx
  src/Pages/Login.jsx
  src/Pages/SignUp.jsx
  src/Pages/SignUpComplete.jsx
  src/Router.js
Labels: enhancement

#17 Feat: 작업되지 않은 페이지들 변경
  src/Pages/BookMark.jsx
  ywave-vite/src/Pages/BookMark.tsx
  ywave-vite/src/Pages/Main.tsx
  ywave-vite/src/Pages/Map.tsx
  ywave-vite/src/Pages/Mypage.tsx
Labels: enhancement

#23 Fix: GlobalStyle 반응형 적용
  ywave-vite/src/Styles/GlobalStyle.ts
Labels: Fix

#29 Feat: GlobalStyle 추가
  ywave-vite/src/Styles/GlobalStyle.ts
Labels: Normal PR

#28 Feat: 메인 페이지 디자인, 메인 장소 페이지 디자인
  ywave-vite/src/Components/LargeReviewBox.tsx
  ywave-vite/src/Components/Navigation.tsx
  ywave-vite/src/Components/PencilButton.tsx
  ywave-vite/src/Components/PlaceBox.tsx
  ywave-vite/src/Components/RecommendBox.tsx
  ywave-vite/src/Components/SmallReviewBox.tsx
  ywave-vite/src/Data/PlaceDatas.tsx
  ywave-vite/src/Images/TitleLogo2.svg
  ywave-vite/src/Pages/CategoryIndustry.tsx
  ywave-vite/src/Pages/CategoryRegion.tsx
  ywave-vite/src/Pages/CategoryResult.tsx
  ywave-vite/src/Pages/Login.tsx
  ywave-vite/src/Pages/Main.tsx
  ywave-vite/src/Pages/MainPlace.tsx
  ywave-vite/src/Pages/Mypage.tsx
  ywave-vite/src/Pages/MypageProfile.tsx
  ywave-vite/src/Pages/MypageReview.tsx
  ywave-vite/src/Pages/SignUp.tsx
  ywave-vite/src/Pages/SignUpComplete.tsx
  ywave-vite/src/Router.tsx
  ywave-vite/src/Styles/GlobalStyle.ts
Labels: Normal PR

#45 Fix: 403 에러 호출 처리
  ywave-vite/src/api/client.ts
Labels: Fix

#48 Feat: 폴더 이모티콘 생성 및 선택
  ywave-vite/src/Components/ConfirmModal.tsx
  ywave-vite/src/Components/EmojiPicker.tsx
  ywave-vite/src/utils/emojiToMarker.ts
Labels: Normal PR

#49 Feat: Review 작성 모달, 데모
  ywave-vite/src/Components/Review/ReviewWriteModal.tsx
  ywave-vite/src/Components/Review/ReviewWriteModalDemo.tsx
Labels: Normal PR

#51 Feat: 카테고리 설정 간단 수정
  ywave-vite/src/Pages/Category/CategoryIndustry.tsx
  ywave-vite/src/Pages/Category/CategoryRegion.tsx
Labels: Normal PR

#52 Fix: API 연동을 위한 카테고리 데이터 수정
  ywave-vite/src/Data/Industries.tsx
  ywave-vite/src/Pages/Category/CategoryIndustry.tsx
  ywave-vite/src/Pages/Category/CategoryResult.tsx
Labels: Fix

#55 Fix: Error 해결
  ywave-vite/src/App.tsx
  ywave-vite/src/Styles/GlobalStyle.ts
  ywave-vite/src/vite-env.d.ts
Labels: Fix

#56 Feat: 선호 카테고리 설정 수정, 선호 지역 설정 UI 변경
  ywave-vite/src/Pages/Category/CategoryIndustry.tsx
  ywave-vite/src/Pages/Category/CategoryRegion.tsx
Labels: Normal PR, Fix

#58 Feat: API 연동 코드 추가 및 type 추가
  ywave-vite/src/api/client.ts
  ywave-vite/src/api/services.ts
  ywave-vite/src/api/types.ts
  ywave-vite/src/hooks/useApi.ts
  ywave-vite/src/vite-env.d.ts
Labels: Normal PR

#59 Fix: 컴포넌트 및 셋팅 일부 수정
  ywave-vite/src/Components/DeleteTag.tsx
  ywave-vite/src/Pages/Setting.tsx
Labels: Fix

#60 Feat: 북마크 관련 1차 기능 추가
  ywave-vite/src/Pages/MainPlace.tsx
Labels: Normal PR

#62 Fix: Emoji 연결 구조 재설정
  ywave-vite/src/Components/BookMarkFolder/FolderBox.tsx
  ywave-vite/src/Components/EmojiPicker.tsx
  ywave-vite/src/utils/categoryMapping.ts
Labels: Fix

#65 Feat: 검색 기능 추가
  ywave-vite/src/Components/MapList/MapList.tsx
  ywave-vite/src/Pages/Map/Map.tsx
Labels: Normal PR

#66 Feat: 검색 기능 추가
  ywave-vite/src/Components/MapList/MapListBottomSheet.tsx
Labels: Normal PR

#69 Feat: 지역 데이터 업로드
  ywave-vite/src/Data/RegionData.tsx
Labels: Normal PR

#70 Feat: 북마크 페이지 API 연동 및 UI 수정
  ywave-vite/src/Components/BookMarkFolder/FolderBox.tsx
  ywave-vite/src/Components/BookMarkFolder/FolderList.tsx
  ywave-vite/src/Components/Review/LargeReviewBox.tsx
  ywave-vite/src/Pages/BookMark/BookMark.tsx
  ywave-vite/src/Pages/BookMark/BookMarkAdd.tsx
  ywave-vite/src/Pages/BookMark/BookMarkEdit.tsx
Labels: Normal PR, Fix, Change

#73 Feat: PlaceId 이용한 구글 API 연결
  ywave-vite/src/Pages/Main/Main.tsx
Labels: Normal PR

#75 Feat: 북마크 상세 페이지 API 연동 및 UI 수정
  ywave-vite/src/Components/BookMarkFolder/FolderList.tsx
  ywave-vite/src/Components/RecommendBox.tsx
  ywave-vite/src/Pages/BookMark/BookMark.tsx
  ywave-vite/src/Pages/BookMark/BookMarkDetail.tsx
  ywave-vite/src/api/services.ts
  ywave-vite/src/api/types.ts
  ywave-vite/src/hooks/useApi.ts
Labels: Normal PR, Fix, Change
